#:kivy 1.0.9

<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 20
        Image: 
            source: 'ico.jpg'
            size_hint_y: None
            height: 300
            allow_stretch: True
        Button:
            text: 'Tarefas'
            on_release: app.root.current = 'tarefas'
        Button:
            text: 'Assistente'
        Button:
            text: 'Sair'
            on_release: app.stop()

<Tarefas>:
    name: 'tarefas'
    BoxLayout:
        orientation: 'vertical'
        
    ScrollView:
        BoxLayout:
            id: box
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            Button:
                text: 'Voltar'
                size_hint_y: None
                height: 40
                size_hint_x: None
                width: 50
                on_release: app.root.current = 'menu'
    BoxLayout:
        size_hint_y: None
        height: 60
        TextInput:
            id: texto
        Button:
            text: '+'
            size_hint_x: None
            width: 60
            on_release: root.addwidget()

<Tarefa>:
    size_hint_y: None
    height: 200
    Label:
        id: label
        font_size: 30
    Button:
        text: 'X'
        size_hint_x: None
        width: 60
        on_release: app.root.get_screen('tarefas').ids.box.remove_widget(root)